### ISSUE TITLE
ERROR: undefined method '[]' for nillClass

### ISSUE THREAD

**Issue by vu-bm** [escapestudios-cookbooks/composer#44]
Hi,
I had done install php 5.3 in centos 6.5 server.
I use the last cookbook ver: 2.0.0
I all ready: include_recipe "composer" in my cookbook
it allway show : ==> default:   8>> include_recipe node['composer']['php_recipe']
with: ==> default: [2015-01-30T02:54:09+00:00] ERROR: undefined method `[]' for nil:NilClass

I had read #37 but not help.
Please help me understand why. 
Thankful.

**Comment by djoos** [comment]
Hi vu-bm,

I spotted you closed the issue yourself - are you up and running with the cookbook now?

Thanks in advance!

Kind regards,
David
