### ISSUE TITLE
Support global install of packages

### ISSUE THREAD

**Issue by daften** [escapestudios-cookbooks/composer#45]
By installing items in a folder in /usr/local with a template file.
Similar to this recipe: https://github.com/escapestudios-cookbooks/phpcs/blob/master/recipes/composer.rb, but then in a LWRP. I can make it, but I'd first check if there's a need for this (I think there is) and if this could make it in :)

**Comment by djoos** [comment]
Hi @daften,

am I right to understand this is also covered in #53?

Thanks in advance!

**Comment by daften** [comment]
Jup, indeed!
