### ISSUE TITLE
Setup config per user use the same global COMPOSER_HOME

### ISSUE THREAD

**Issue by Maks3w** [escapestudios-cookbooks/composer#47]
Actual implementation of COMPOSER_HOME is not per user aware.

Create composer_home is not synced with env var and is not per user aware.

```
  configs.each_pair do |user, user_configs|
  directory "/home/#{user}/.composer" do
      owner user
      group user
      mode 0755
      action :create
    end

  # but later

  environment 'COMPOSER_HOME' => Composer.home_dir(node)
```

So `Composer.home_dir(node)` is global and does not match with `/home/#{user}/.composer`

**Comment by djoos** [comment]
Fixed in @john-coleman-w's PR!
